version: 2

references:
  set_environment_variables: &set_environment_variables
    run:
      name: Set Environment Variables
      command: |
        echo 'export CI_SHA1=$CIRCLE_SHA1' >> ${BASH_ENV}
        echo 'export CI_BRANCH=$CIRCLE_BRANCH' >> ${BASH_ENV}
        echo 'export CI_BUILD_NUM=$CIRCLE_BUILD_NUM' >> ${BASH_ENV}
        echo 'export CI_TAG=$CIRCLE_TAG' >> ${BASH_ENV}
        echo 'export ROK8S_INSTALL_PATH=${HOME}' >> ${BASH_ENV}

  build_image: &build_image
    run:
      name: Build Docker Image
      command: |
        docker login quay.io -u="${QUAY_USER}" -p="${QUAY_TOKEN}"
        docker-pull -f deploy/build_and_deploy.config
        docker-build -f deploy/build_and_deploy.config
        docker-push -f deploy/build_and_deploy.config

  deploy_to_kube: &deploy_to_kube
    run:
      name: Deploy to Kubernetes
      command: |
        prepare-kubectl
        helm-deploy -f deploy/build_and_deploy.config

  ephemeral_deploy: &ephemeral_deploy
    run:
      name: Deploy to Ephemeral Environment
      command: |
        deploy/create-ephemeral-values.sh $NAMESPACE
        prepare-kubectl
        "(kubectl get ns $NAMESPACE || kubectl create ns $NAMESPACE) && kubectl label namespace $NAMESPACE environment=ephemeral --overwrite=true"
        "k8s-deploy -f ${ROK8S_CONFIG}"
        "helm-deploy -f ${ROK8S_CONFIG}"
        "k8s-verify-deployment -f ${ROK8S_CONFIG}"
        "echo \"Ephemeral URL: https://${NAMESPACE}.bb-complete.hillghost.com\""

jobs:
  build_image:
    docker:
      - image: quay.io/reactiveops/ci-images:v9-alpine
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *build_image
  deploy_to_kube:
    docker:
      - image: quay.io/reactiveops/ci-images:v9-alpine
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - *deploy_to_kube
  ephemeral_deploy:
    docker:
      - image: quay.io/reactiveops/ci-images:v9-alpine
    steps:
      - checkout
      - setup_remote_docker
      - *set_environment_variables
      - run: echo 'export NAMESPACE=$(echo $CIRCLE_BRANCH | cut -c 1-63 | sed "s/[^a-zA-Z0-9-]/-/g")' >> ${BASH_ENV}
      - *ephemeral_deploy
    environment:
      ROK8S_CONFIG: deploy/ephemeral.config

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_image
      - deploy_to_kube:
          requires:
            - build_image
          filters:
            branches:
              only: master
      - ephemeral_deploy:
          requires:
            - build_image
          filters:
            branches:
              only:
                - /feature-.*/

  