ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
  paths:
    - /
  hosts:
    - host: taco-tuesday.bb-complete.hillghost.com
      paths: ["/"]
  tls:
    - secretName: taco-tuesday-cert
      hosts:
        - taco-tuesday.bb-complete.hillghost.com